USE ECOMMERCEDB;
-- USING AGGREGATE FUNCTIONS
SELECT * FROM ORDER_ITEMS;
SELECT P.NAME,SUM(P.PRICE * OI.QUANTITY) AS TOTAL_PRICE FROM PRODUCTS P JOIN ORDER_ITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID GROUP BY NAME 
ORDER BY TOTAL_PRICE ;
SELECT SUM(PRICE) AS TOTAL_REVENUE FROM ORDER_ITEMS;
SELECT AVG(QUANTITY) AS AVERAGE_ORDERS FROM ORDER_ITEMS;
SELECT MAX(PRICE) AS MAX_PURCHASE FROM ORDER_ITEMS;
SELECT MIN(PRICE) AS MIN_COST FROM PRODUCTS;
SELECT COUNT(*) FROM ORDERS;
SELECT P.PRODUCT_ID,P.NAME AS PRODUCT_NAME,SUM(OI.QUANTITY*P.PRICE) AS PRODUCTSALES,SUM(OI.QUANTITY) AS UNITSSOLD
FROM ORDER_ITEMS OI
JOIN PRODUCTS P ON OI.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.NAME
ORDER BY PRODUCTSALES DESC
LIMIT 1;